run_mode: "local"
http_listen_addr: ":8095"
google_project_id: "gemini-power-test"
identity_service_url: "http://localhost:3000"
firestore:
  bundle_collection: "CacheBundles"
  files_collection: "Files"
  profiles_collection: "FilterProfiles"
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:4200" 
    - "http://localhost:8080"
  cors_role: "llm-client"